
export  const FETCH_TODOS = "FETCH_TODOS";

export const ADD_TODO="ADD_TODO";

export const DELETE_TODO="DELETE_TODO";

export const UPDATE_TODO_STATUS="UPDATE_TODO_STATUS";

export const CATCH_TODO_ERROR="CATCH_TODO_ERROR";

export const TODO_TOGGLE_STATUS="TODO_TOGGLE_STATUS";